site_name: Ivy Documentation
docs_dir: src
nav:
    - Welcome: index.md
    - Token: token.md
    - Amounts: amounts.md
    - Games: games.md
    - Identifiers: identifiers.md
    - Authentication: authentication.md
    - Deposits: deposits.md
    - Withdrawals: withdrawals.md
    - Example 1 - Cat: example-1-cat.md
    - Example 2 - Leaderboard: example-2-leaderboard.md
    - Example 3 - Faucet: example-3-faucet.md
theme:
    name: mkdocs
    highlightjs: true
