[package]
name = "ivy-aggregator"
version = "0.1.0"
edition = "2021"

[dependencies]
bs58 = "0.5.1"
hex = "0.4.3"
priority-queue = "2.3.1"
rouille = "3.6.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
ureq = { version = "3.0.10", features = ["json"] }
