name: Build and Export Artifacts
permissions:
  contents: read

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: |
          ivy-backend/package-lock.json
          ivy-react/package-lock.json
          ivy-sdk/package-lock.json

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Set up Bazel
      uses: bazel-contrib/setup-bazel@0.8.5
      with:
        bazelisk-cache: true
        disk-cache: ${{ github.workflow }}
        repository-cache: true
        bazelisk-version: '1.x'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Install Solana + Anchor
      run: |
        curl --proto '=https' --tlsv1.2 -sSfL https://solana-install.solana.workers.dev | bash
        echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        echo "/home/runner/.avm/bin" >> $GITHUB_PATH

    - name: Build all targets
      run: |
        bazel build //...

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: all-artifacts
        path: bazel-bin/
